import { useState } from 'react';
import { api } from '../lib/api';
import type { ProposedConnector } from '../lib/types';
import { useToast } from '../contexts/ToastContext';

interface AiConnectorModalProps {
  open: boolean;
  onClose: () => void;
  onSaved: () => void;
}

export function AiConnectorModal({ open, onClose, onSaved }: AiConnectorModalProps) {
  const { showToast } = useToast();
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [proposal, setProposal] = useState<ProposedConnector | null>(null);
  const [source, setSource] = useState<string>('');

  if (!open) return null;

  async function handleGenerate() {
    if (!description.trim()) return;
    setLoading(true);
    setProposal(null);
    try {
      const data = await api<{ proposal: ProposedConnector; source: string }>(
        '/ai/propose-connector',
        { method: 'POST', body: JSON.stringify({ description: description.trim() }) },
      );
      setProposal(data.proposal);
      setSource(data.source);
      showToast(
        data.source === 'gemini'
          ? 'Config generated by Gemini'
          : 'Config generated (demo pattern match)',
      );
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Generation failed', 'error');
    } finally {
      setLoading(false);
    }
  }

  async function handleSave() {
    if (!proposal) return;
    setSaving(true);
    try {
      await api('/fivetran/add-connector', {
        method: 'POST',
        body: JSON.stringify({
          id: proposal.id,
          name: proposal.name,
          source: proposal.source,
          destination: proposal.destination,
          schedule: proposal.schedule,
          tables: proposal.tables,
        }),
      });
      showToast(`Connector ${proposal.name} saved to demo environment`);
      setDescription('');
      setProposal(null);
      onSaved();
      onClose();
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Save failed', 'error');
    } finally {
      setSaving(false);
    }
  }

  function handleClose() {
    setProposal(null);
    onClose();
  }

  return (
    <div className="drawer-overlay" onClick={handleClose}>
      <aside className="drawer drawer--wide" onClick={(e) => e.stopPropagation()}>
        <div className="drawer__header">
          <div>
            <h2>Add connector with AI</h2>
            <p className="muted">Gemini generates a pipeline config from your description</p>
          </div>
          <button type="button" className="btn btn--ghost btn--sm" onClick={handleClose}>
            ✕
          </button>
        </div>

        <label className="form-field">
          <span>Describe the connector</span>
          <textarea
            className="ai-textarea"
            rows={4}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="e.g. Sync Shopify orders into BigQuery daily&#10;e.g. Ingest Zendesk tickets into BigQuery with full history"
          />
        </label>

        <button
          type="button"
          className="btn btn--primary"
          disabled={loading || !description.trim()}
          onClick={handleGenerate}
        >
          {loading ? 'Asking Gemini…' : '✨ Ask Gemini to generate config'}
        </button>

        {proposal && (
          <div className="ai-proposal card">
            <div className="ai-proposal__header">
              <h3>Proposed configuration</h3>
              {source && (
                <span className="badge badge--info">
                  {source === 'gemini' ? 'Gemini' : 'Demo pattern'}
                </span>
              )}
            </div>
            <dl className="ai-proposal__grid">
              <dt>Name</dt>
              <dd>{proposal.name}</dd>
              <dt>ID</dt>
              <dd><code>{proposal.id}</code></dd>
              <dt>Source</dt>
              <dd>{proposal.source}</dd>
              <dt>Destination</dt>
              <dd>{proposal.destination}</dd>
              <dt>Schedule</dt>
              <dd>{proposal.schedule}</dd>
              <dt>Tables</dt>
              <dd>{proposal.tables.join(', ')}</dd>
              <dt>Notes</dt>
              <dd>{proposal.notes}</dd>
            </dl>
            <button
              type="button"
              className="btn btn--primary btn--full"
              disabled={saving}
              onClick={handleSave}
            >
              {saving ? 'Saving…' : 'Save demo connector'}
            </button>
          </div>
        )}
      </aside>
    </div>
  );
}
