/* AROA API — generated by backend/scripts/build-vercel-api.mjs */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/app.ts
var app_exports = {};
__export(app_exports, {
  createApp: () => createApp,
  default: () => app_default
});
module.exports = __toCommonJS(app_exports);
var import_cors = __toESM(require("cors"), 1);
var import_express8 = __toESM(require("express"), 1);

// src/config.ts
var import_dotenv = __toESM(require("dotenv"), 1);
var import_zod = require("zod");
import_dotenv.default.config();
function defaultFrontendOrigin() {
  if (process.env.FRONTEND_ORIGIN) return process.env.FRONTEND_ORIGIN;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`;
  return "http://localhost:5173";
}
var envSchema = import_zod.z.object({
  PORT: import_zod.z.coerce.number().default(3001),
  NODE_ENV: import_zod.z.enum(["development", "production", "test"]).default("development"),
  GEMINI_API_KEY: import_zod.z.string().min(1).optional(),
  AGENT_ID: import_zod.z.string().min(1).optional(),
  FRONTEND_ORIGIN: import_zod.z.string().url().optional(),
  VERCEL_URL: import_zod.z.string().optional()
});
var parsed = envSchema.safeParse(process.env);
if (!parsed.success) {
  console.error("Invalid environment configuration:", parsed.error.flatten().fieldErrors);
  console.warn("Using placeholder config \u2014 set GEMINI_API_KEY and AGENT_ID in .env for chat.");
}
var raw = parsed.success ? parsed.data : {
  PORT: Number(process.env.PORT) || 3001,
  NODE_ENV: process.env.NODE_ENV || "development",
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  AGENT_ID: process.env.AGENT_ID,
  FRONTEND_ORIGIN: void 0,
  VERCEL_URL: process.env.VERCEL_URL
};
var config = {
  ...raw,
  GEMINI_API_KEY: raw.GEMINI_API_KEY || "your_gemini_api_key",
  AGENT_ID: raw.AGENT_ID || "agents/YOUR_AGENT_ID",
  FRONTEND_ORIGIN: raw.FRONTEND_ORIGIN ?? defaultFrontendOrigin(),
  VERCEL_URL: raw.VERCEL_URL ? `https://${raw.VERCEL_URL}` : void 0
};

// src/routes/fivetran.ts
var import_express = require("express");

// src/services/fivetranService.ts
var mins = (m) => new Date(Date.now() - m * 60 * 1e3).toISOString();
var minsFuture = (m) => new Date(Date.now() + m * 60 * 1e3).toISOString();
var secsAgo = (s) => new Date(Date.now() - s * 1e3).toISOString();
function withSyncTimestamps(finishedMinutesAgo, durationSeconds, partial) {
  const finishedAt = mins(finishedMinutesAgo);
  const startedAt = secsAgo(finishedMinutesAgo * 60 + durationSeconds);
  return {
    ...partial,
    lastSyncStartedAt: startedAt,
    lastSyncFinishedAt: finishedAt,
    lastSyncAt: finishedAt,
    nextSyncAt: partial.nextSyncAt ?? minsFuture(30),
    primaryTable: partial.primaryTable,
    tables: partial.tables,
    errorMessage: partial.errorMessage
  };
}
var demoConnectors = [
  withSyncTimestamps(10, 364, {
    id: "conn_salesforce_001",
    name: "Salesforce \xE2\u2020\u2019 BigQuery",
    source: "Salesforce",
    destination: "BigQuery",
    status: "active",
    syncState: "scheduled",
    schedule: "every 30 minutes",
    nextSyncAt: minsFuture(20),
    lastSyncStatus: "succeeded",
    avgSyncDurationSeconds: 372,
    rowsProcessedLastSync: 142891,
    rowsInsertedLastSync: 1240,
    rowsUpdatedLastSync: 140820,
    rowsDeletedLastSync: 831,
    schemaVersion: "v2.4.1",
    primaryTable: "crm.salesforce_accounts",
    tables: ["accounts", "opportunities", "contacts"]
  }),
  withSyncTimestamps(300, 420, {
    id: "conn_ga4_001",
    name: "GA4 \xE2\u2020\u2019 BigQuery",
    source: "Google Analytics 4",
    destination: "BigQuery",
    status: "failed",
    syncState: "broken",
    schedule: "every 1 hour",
    nextSyncAt: minsFuture(0),
    lastSyncStatus: "failed",
    avgSyncDurationSeconds: 890,
    rowsProcessedLastSync: 0,
    rowsInsertedLastSync: 0,
    rowsUpdatedLastSync: 0,
    rowsDeletedLastSync: 0,
    schemaVersion: "v1.8.0",
    errorMessage: "Schema change detected: new column event_params.custom_dimension_12 added in source. Sync blocked pending schema update.",
    primaryTable: "analytics.ga4_events_daily",
    tables: ["events_daily", "events_intraday", "user_properties"]
  }),
  withSyncTimestamps(12, 228, {
    id: "conn_postgres_001",
    name: "Postgres \xE2\u2020\u2019 BigQuery",
    source: "PostgreSQL",
    destination: "BigQuery",
    status: "active",
    syncState: "scheduled",
    schedule: "every 15 minutes",
    nextSyncAt: minsFuture(3),
    lastSyncStatus: "succeeded",
    avgSyncDurationSeconds: 215,
    rowsProcessedLastSync: 8412,
    rowsInsertedLastSync: 620,
    rowsUpdatedLastSync: 7680,
    rowsDeletedLastSync: 112,
    schemaVersion: "v3.1.0",
    primaryTable: "warehouse.postgres_orders",
    tables: ["orders", "order_items", "inventory"]
  }),
  withSyncTimestamps(40, 540, {
    id: "conn_shopify_001",
    name: "Shopify \xE2\u2020\u2019 BigQuery",
    source: "Shopify",
    destination: "BigQuery",
    status: "active",
    syncState: "scheduled",
    schedule: "every 1 hour",
    nextSyncAt: minsFuture(20),
    lastSyncStatus: "partial",
    avgSyncDurationSeconds: 612,
    rowsProcessedLastSync: 12400,
    rowsInsertedLastSync: 11950,
    rowsUpdatedLastSync: 420,
    rowsDeletedLastSync: 30,
    schemaVersion: "v1.2.3",
    errorMessage: "Partial sync: 12,400 of 12,850 order rows loaded \xE2\u20AC\u201D API rate limit hit mid-sync.",
    primaryTable: "commerce.shopify_orders",
    tables: ["orders", "order_items", "customers", "products"]
  }),
  withSyncTimestamps(1440, 1800, {
    id: "conn_marketo_001",
    name: "Marketo \xE2\u2020\u2019 BigQuery",
    source: "Marketo",
    destination: "BigQuery",
    status: "paused",
    syncState: "paused",
    schedule: "every 6 hours",
    nextSyncAt: minsFuture(0),
    lastSyncStatus: "succeeded",
    avgSyncDurationSeconds: 1920,
    rowsProcessedLastSync: 284500,
    rowsInsertedLastSync: 12400,
    rowsUpdatedLastSync: 271800,
    rowsDeletedLastSync: 300,
    schemaVersion: "v0.9.2",
    primaryTable: "marketing.marketo_leads",
    tables: ["leads", "campaigns", "activities"]
  }),
  withSyncTimestamps(95, 2820, {
    id: "conn_zendesk_001",
    name: "Zendesk \xE2\u2020\u2019 BigQuery",
    source: "Zendesk",
    destination: "BigQuery",
    status: "warning",
    syncState: "degraded",
    schedule: "every 30 minutes",
    nextSyncAt: minsFuture(5),
    lastSyncStatus: "partial",
    avgSyncDurationSeconds: 2640,
    rowsProcessedLastSync: 18200,
    rowsInsertedLastSync: 4100,
    rowsUpdatedLastSync: 13800,
    rowsDeletedLastSync: 300,
    schemaVersion: "v1.0.4",
    errorMessage: "Slow sync: last run took 47m (SLA 30m). Ticket updates may be delayed up to 2h.",
    primaryTable: "support.zendesk_tickets",
    tables: ["tickets", "users", "organizations"]
  })
];
var demoLogs = [
  { timestamp: mins(10), level: "info", message: "Sync completed \xE2\u20AC\u201D 142,891 rows in 6m 04s", connectorId: "conn_salesforce_001" },
  { timestamp: mins(40), level: "info", message: "Incremental sync started for Account, Opportunity objects", connectorId: "conn_salesforce_001" },
  { timestamp: mins(70), level: "info", message: "Schema validation passed \xE2\u20AC\u201D no drift detected", connectorId: "conn_salesforce_001" },
  { timestamp: mins(300), level: "info", message: "Sync started for conn_ga4_001", connectorId: "conn_ga4_001" },
  { timestamp: mins(298), level: "warn", message: "Detected schema drift: 1 new column in events_intraday_*", connectorId: "conn_ga4_001" },
  { timestamp: mins(297), level: "error", message: "Sync failed for conn_ga4_001: unexpected column event_params.custom_dimension_12", connectorId: "conn_ga4_001" },
  { timestamp: mins(240), level: "error", message: "Retry 2/3 failed \xE2\u20AC\u201D destination schema out of date", connectorId: "conn_ga4_001" },
  { timestamp: mins(12), level: "info", message: "Sync completed \xE2\u20AC\u201D 8,412 rows across 3 tables", connectorId: "conn_postgres_001" },
  { timestamp: mins(27), level: "info", message: "Connection pool healthy \xE2\u20AC\u201D latency 42ms", connectorId: "conn_postgres_001" },
  { timestamp: mins(40), level: "warn", message: "Partial sync: 450 order rows skipped due to API rate limit", connectorId: "conn_shopify_001" },
  { timestamp: mins(41), level: "info", message: "Loaded 12,400 / 12,850 rows \xE2\u20AC\u201D will retry remainder next sync", connectorId: "conn_shopify_001" },
  { timestamp: mins(1440), level: "info", message: "Connector paused by operator \xE2\u20AC\u201D maintenance window", connectorId: "conn_marketo_001" },
  { timestamp: mins(1500), level: "warn", message: "Last successful sync before pause \xE2\u20AC\u201D 24h ago", connectorId: "conn_marketo_001" },
  { timestamp: mins(95), level: "warn", message: "Sync duration 47m exceeds SLA threshold (30m)", connectorId: "conn_zendesk_001" },
  { timestamp: mins(96), level: "error", message: "High latency detected \xE2\u20AC\u201D only 62% of ticket updates applied", connectorId: "conn_zendesk_001" },
  { timestamp: mins(125), level: "warn", message: "Auth token refreshed \xE2\u20AC\u201D connection restored", connectorId: "conn_zendesk_001" }
];
var HISTORY_PROFILES = {
  conn_salesforce_001: { baseDuration: 372, variance: 40, successRate: 1, rowsBase: 14e4 },
  conn_ga4_001: { baseDuration: 890, variance: 120, successRate: 0.35, rowsBase: 24e5 },
  conn_postgres_001: { baseDuration: 215, variance: 25, successRate: 1, rowsBase: 8e3 },
  conn_shopify_001: { baseDuration: 612, variance: 90, successRate: 0.75, rowsBase: 12500 },
  conn_marketo_001: { baseDuration: 1920, variance: 200, successRate: 0.9, rowsBase: 28e4 },
  conn_zendesk_001: { baseDuration: 2640, variance: 400, successRate: 0.5, rowsBase: 18e3 }
};
var SCHEMA_CHANGES = {
  conn_ga4_001: [
    {
      timestamp: mins(302),
      eventType: "alter_table",
      objectType: "column",
      tableName: "analytics.ga4_events_daily",
      columnName: "event_params.custom_dimension_12",
      details: "New column event_params.custom_dimension_12 added in GA4 source \xE2\u20AC\u201D sync blocked pending schema update."
    },
    {
      timestamp: mins(720),
      eventType: "alter_table",
      objectType: "column",
      tableName: "analytics.ga4_events_intraday",
      columnName: "event_params.session_engaged",
      details: "Column type widened from BOOL to STRING in source property."
    },
    {
      timestamp: mins(2880),
      eventType: "create_table",
      objectType: "table",
      tableName: "analytics.ga4_user_properties",
      details: "New table user_properties enabled in connector config."
    }
  ],
  conn_shopify_001: [
    {
      timestamp: mins(180),
      eventType: "alter_table",
      objectType: "column",
      tableName: "commerce.shopify_orders",
      columnName: "discount_codes",
      details: "New array column discount_codes detected on orders object."
    },
    {
      timestamp: mins(1440),
      eventType: "alter_table",
      objectType: "column",
      tableName: "commerce.shopify_orders",
      columnName: "fulfillment_status",
      details: 'Enum value "partially_fulfilled" added in Shopify API.'
    }
  ],
  conn_salesforce_001: [
    {
      timestamp: mins(4320),
      eventType: "alter_table",
      objectType: "column",
      tableName: "crm.salesforce_opportunities",
      columnName: "ai_score",
      details: "Salesforce added AI scoring field on Opportunity object."
    }
  ],
  conn_zendesk_001: [
    {
      timestamp: mins(480),
      eventType: "alter_table",
      objectType: "column",
      tableName: "support.zendesk_tickets",
      columnName: "satisfaction_rating",
      details: "Nullable column satisfaction_rating added \xE2\u20AC\u201D no breaking change."
    }
  ],
  conn_postgres_001: [
    {
      timestamp: mins(10080),
      eventType: "create_table",
      objectType: "table",
      tableName: "warehouse.postgres_inventory",
      details: "New inventory table added to replication set."
    }
  ],
  conn_marketo_001: [
    {
      timestamp: mins(2160),
      eventType: "drop_table",
      objectType: "table",
      tableName: "marketing.marketo_legacy_activities",
      details: "Deprecated activities table removed from source \xE2\u20AC\u201D paused during migration."
    }
  ]
};
var USAGE_SUMMARY = [
  {
    connectorId: "conn_ga4_001",
    connectorName: "GA4 \xE2\u2020\u2019 BigQuery",
    marThisMonth: 482e5,
    marLastMonth: 448e5,
    estCreditsThisMonth: 482,
    estCreditsLastMonth: 448
  },
  {
    connectorId: "conn_salesforce_001",
    connectorName: "Salesforce \xE2\u2020\u2019 BigQuery",
    marThisMonth: 124e5,
    marLastMonth: 119e5,
    estCreditsThisMonth: 124,
    estCreditsLastMonth: 119
  },
  {
    connectorId: "conn_shopify_001",
    connectorName: "Shopify \xE2\u2020\u2019 BigQuery",
    marThisMonth: 98e5,
    marLastMonth: 82e5,
    estCreditsThisMonth: 98,
    estCreditsLastMonth: 82
  },
  {
    connectorId: "conn_zendesk_001",
    connectorName: "Zendesk \xE2\u2020\u2019 BigQuery",
    marThisMonth: 61e5,
    marLastMonth: 54e5,
    estCreditsThisMonth: 61,
    estCreditsLastMonth: 54
  },
  {
    connectorId: "conn_marketo_001",
    connectorName: "Marketo \xE2\u2020\u2019 BigQuery",
    marThisMonth: 32e5,
    marLastMonth: 345e4,
    estCreditsThisMonth: 32,
    estCreditsLastMonth: 35
  },
  {
    connectorId: "conn_postgres_001",
    connectorName: "Postgres \xE2\u2020\u2019 BigQuery",
    marThisMonth: 185e4,
    marLastMonth: 172e4,
    estCreditsThisMonth: 19,
    estCreditsLastMonth: 17
  }
];
function defaultHealthMetrics() {
  return {
    avgSyncDurationSeconds: 300,
    rowsProcessedLastSync: 0,
    rowsInsertedLastSync: 0,
    rowsUpdatedLastSync: 0,
    rowsDeletedLastSync: 0
  };
}
function listConnectors() {
  return [...demoConnectors];
}
function getConnectorStatus(connectorId) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) {
    return { found: false, connectorId };
  }
  const health = connector.status === "active" ? "green" : connector.status === "warning" ? "yellow" : "red";
  return {
    found: true,
    connector,
    syncHealth: health,
    nextScheduledSync: connector.nextSyncAt
  };
}
function getConnectorLogs(connectorId, timeRangeHours = 24) {
  const cutoff = Date.now() - timeRangeHours * 60 * 60 * 1e3;
  const logs = demoLogs.filter(
    (log) => log.connectorId === connectorId && new Date(log.timestamp).getTime() >= cutoff
  ).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  return { connectorId, timeRangeHours, count: logs.length, logs };
}
function getConnectorHistory(connectorId) {
  const profile = HISTORY_PROFILES[connectorId];
  if (!profile) {
    return { connectorId, runs: [] };
  }
  const runs = [];
  let cursorMinutes = 30;
  for (let i = 0; i < 10; i++) {
    const durationSeconds = Math.round(
      profile.baseDuration + Math.sin(i * 1.7) * profile.variance / 2
    );
    const roll = (i * 17 + connectorId.length) % 10;
    const status = i === 0 && connectorId === "conn_ga4_001" ? "failed" : i === 0 && connectorId === "conn_zendesk_001" ? "partial" : roll / 10 < profile.successRate ? i === 3 && connectorId === "conn_shopify_001" ? "partial" : "succeeded" : roll % 2 === 0 ? "partial" : "failed";
    const finishedAt = mins(cursorMinutes);
    const startedAt = secsAgo(cursorMinutes * 60 + durationSeconds);
    const rowsProcessed = status === "failed" ? 0 : Math.round(profile.rowsBase * (0.85 + i % 3 * 0.05));
    runs.push({
      startedAt,
      finishedAt,
      status,
      durationSeconds,
      rowsProcessed
    });
    cursorMinutes += connectorId === "conn_zendesk_001" ? 90 : connectorId === "conn_marketo_001" ? 360 : 60;
  }
  return { connectorId, runs };
}
function getSchemaChanges(connectorId) {
  const changes = [...SCHEMA_CHANGES[connectorId] ?? []].sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  );
  return { connectorId, changes };
}
function getUsageSummary() {
  return {
    usage: [...USAGE_SUMMARY].sort((a, b) => b.marThisMonth - a.marThisMonth),
    refreshedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
}
function addConnector(input) {
  const now = /* @__PURE__ */ new Date();
  const health = defaultHealthMetrics();
  const connector = {
    ...input,
    ...health,
    syncState: input.status === "paused" ? "paused" : "scheduled",
    lastSyncStartedAt: now.toISOString(),
    lastSyncFinishedAt: now.toISOString(),
    lastSyncAt: now.toISOString(),
    nextSyncAt: new Date(now.getTime() + 15 * 60 * 1e3).toISOString(),
    lastSyncStatus: "succeeded",
    schemaVersion: "v1.0.0",
    status: input.status ?? "active"
  };
  demoConnectors.push(connector);
  HISTORY_PROFILES[connector.id] = {
    baseDuration: 300,
    variance: 60,
    successRate: 0.95,
    rowsBase: 1e4
  };
  demoLogs.unshift({
    timestamp: now.toISOString(),
    level: "info",
    message: `Connector ${connector.id} created via AI-assisted setup`,
    connectorId: connector.id
  });
  return connector;
}
function triggerSync(connectorId) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) return { success: false, connectorId, message: "Connector not found" };
  connector.status = "syncing";
  connector.syncState = "syncing";
  connector.lastSyncStatus = "running";
  return {
    success: true,
    connectorId,
    syncId: `sync_${Date.now()}`,
    message: `Sync triggered for ${connector.name}`,
    estimatedDurationMinutes: 12
  };
}
function updateConnectorSchema(connectorId, schemaConfig) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) return { success: false, connectorId, message: "Connector not found" };
  const now = /* @__PURE__ */ new Date();
  connector.status = "active";
  connector.syncState = "scheduled";
  connector.lastSyncStatus = "succeeded";
  connector.errorMessage = void 0;
  connector.schemaVersion = `v${(parseFloat(connector.schemaVersion.replace("v", "")) + 0.1).toFixed(1)}`;
  connector.lastSyncStartedAt = secsAgo(420);
  connector.lastSyncFinishedAt = now.toISOString();
  connector.lastSyncAt = now.toISOString();
  connector.nextSyncAt = new Date(Date.now() + 30 * 60 * 1e3).toISOString();
  return {
    success: true,
    connectorId,
    schemaVersion: connector.schemaVersion,
    appliedConfig: schemaConfig,
    message: "Schema updated successfully."
  };
}
function pauseConnector(connectorId) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) return { success: false, connectorId, message: "Connector not found" };
  connector.status = "paused";
  connector.syncState = "paused";
  return { success: true, connectorId, status: connector.status };
}
function resumeConnector(connectorId) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) return { success: false, connectorId, message: "Connector not found" };
  connector.status = connector.lastSyncStatus === "failed" ? "failed" : "active";
  connector.syncState = connector.status === "failed" ? "broken" : "scheduled";
  return { success: true, connectorId, status: connector.status };
}
function scheduleToMinutes(schedule) {
  const s = schedule.toLowerCase();
  if (s.includes("15 minute")) return 15;
  if (s.includes("30 minute")) return 30;
  if (s.includes("1 hour") || s === "hourly") return 60;
  if (s.includes("6 hour")) return 360;
  if (s.includes("12 hour")) return 720;
  if (s.includes("daily") || s.includes("24 hour")) return 1440;
  return 60;
}
function updateConnector(connectorId, updates) {
  const connector = demoConnectors.find((c) => c.id === connectorId);
  if (!connector) return { success: false, connectorId, message: "Connector not found" };
  if (updates.name?.trim()) {
    connector.name = updates.name.trim();
  }
  if (updates.schedule?.trim()) {
    connector.schedule = updates.schedule.trim();
    const intervalMin = scheduleToMinutes(connector.schedule);
    connector.nextSyncAt = new Date(Date.now() + intervalMin * 60 * 1e3).toISOString();
  }
  demoLogs.unshift({
    timestamp: (/* @__PURE__ */ new Date()).toISOString(),
    level: "info",
    message: `Connector ${connectorId} updated \u2014 schedule: ${connector.schedule}`,
    connectorId
  });
  return { success: true, connector };
}

// src/routes/fivetran.ts
var router = (0, import_express.Router)();
router.post("/list-connectors", (_req, res) => {
  res.json({ connectors: listConnectors() });
});
router.post("/get-connector-status", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(getConnectorStatus(connectorId));
});
router.post("/get-connector-history", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(getConnectorHistory(connectorId));
});
router.post("/get-schema-changes", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(getSchemaChanges(connectorId));
});
router.get("/usage-summary", (_req, res) => {
  res.json(getUsageSummary());
});
router.post("/get-connector-logs", (req, res) => {
  const { connectorId, timeRangeHours } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(getConnectorLogs(connectorId, timeRangeHours ?? 24));
});
router.post("/trigger-sync", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(triggerSync(connectorId));
});
router.post("/update-connector-schema", (req, res) => {
  const { connectorId, schemaConfig } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(updateConnectorSchema(connectorId, schemaConfig ?? {}));
});
router.post("/update-connector", (req, res) => {
  const { connectorId, name, schedule } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  const result = updateConnector(connectorId, { name, schedule });
  if (!result.success) {
    res.status(404).json(result);
    return;
  }
  res.json(result);
});
router.post("/pause-connector", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(pauseConnector(connectorId));
});
router.post("/resume-connector", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(resumeConnector(connectorId));
});
router.post("/add-connector", (req, res) => {
  const body = req.body;
  if (!body.id || !body.name || !body.source) {
    res.status(400).json({ error: "id, name, and source are required" });
    return;
  }
  const connector = addConnector({
    id: body.id,
    name: body.name,
    source: body.source,
    destination: body.destination ?? "BigQuery",
    status: body.status ?? "active",
    schedule: body.schedule ?? "every 1 hour",
    tables: body.tables,
    primaryTable: body.tables?.[0] ? `demo-analytics-prod.${body.source.toLowerCase().replace(/\s+/g, "_")}.${body.tables[0]}` : void 0
  });
  res.status(201).json({ success: true, connector });
});
var fivetran_default = router;

// src/routes/elastic.ts
var import_express2 = require("express");

// src/services/elasticService.ts
var mins2 = (m) => new Date(Date.now() - m * 60 * 1e3).toISOString();
var syntheticLogs = [
  { timestamp: mins2(15), level: "ERROR", service: "pipeline-service", connectorId: "conn_ga4_001", message: "Sync failed for conn_ga4_001: unexpected column event_params.custom_dimension_12", index: "pipeline-logs-*" },
  { timestamp: mins2(22), level: "ERROR", service: "pipeline-service", connectorId: "conn_ga4_001", message: "Schema mismatch on events_intraday \u2014 sync aborted after 3 retries", index: "pipeline-logs-*" },
  { timestamp: mins2(35), level: "WARN", service: "pipeline-service", connectorId: "conn_zendesk_001", message: "High latency detected in pipeline-service \u2014 Zendesk sync 47m (SLA 30m)", index: "pipeline-logs-*" },
  { timestamp: mins2(40), level: "WARN", service: "pipeline-service", connectorId: "conn_shopify_001", message: "Partial sync for conn_shopify_001 \u2014 450 rows deferred to next run", index: "pipeline-logs-*" },
  { timestamp: mins2(55), level: "ERROR", service: "api-gateway", connectorId: "conn_postgres_001", message: "Auth error when connecting to Postgres source \u2014 token expired, auto-refreshed", index: "pipeline-logs-*" },
  { timestamp: mins2(90), level: "INFO", service: "pipeline-service", connectorId: "conn_salesforce_001", message: "Sync completed \u2014 142,891 rows loaded in 6m 04s", index: "pipeline-logs-*" },
  { timestamp: mins2(120), level: "INFO", service: "billing-service", message: "Daily billing reconciliation job started", index: "pipeline-logs-*" },
  { timestamp: mins2(180), level: "WARN", service: "bigquery-loader", connectorId: "conn_ga4_001", message: "Data freshness SLA breached for analytics.ga4_events_daily (300 min late)", index: "pipeline-logs-*" },
  { timestamp: mins2(240), level: "INFO", service: "api-gateway", connectorId: "conn_postgres_001", message: "Postgres connector heartbeat OK \u2014 8,412 rows synced", index: "pipeline-logs-*" },
  { timestamp: mins2(360), level: "ERROR", service: "pipeline-service", connectorId: "conn_marketo_001", message: "Connector conn_marketo_001 paused \u2014 no sync in 24h, attribution data stale", index: "pipeline-logs-*" },
  { timestamp: mins2(420), level: "INFO", service: "billing-service", message: "Usage metering export completed \u2014 2,500 events processed", index: "pipeline-logs-*" },
  { timestamp: mins2(480), level: "WARN", service: "api-gateway", message: "Elevated 429 rate from Shopify API \u2014 throttling applied", index: "pipeline-logs-*" },
  { timestamp: mins2(600), level: "ERROR", service: "pipeline-service", connectorId: "conn_ga4_001", message: "Retry 1/3 failed \u2014 destination schema out of date", index: "pipeline-logs-*" },
  { timestamp: mins2(720), level: "WARN", service: "pipeline-service", connectorId: "conn_zendesk_001", message: "Zendesk pagination timeout \u2014 batch 14 of 22 incomplete", index: "pipeline-logs-*" },
  { timestamp: mins2(900), level: "INFO", service: "pipeline-service", connectorId: "conn_shopify_001", message: "Shopify sync completed \u2014 12,850 orders loaded", index: "pipeline-logs-*" },
  { timestamp: mins2(1080), level: "ERROR", service: "bigquery-loader", connectorId: "conn_ga4_001", message: "Load job failed \u2014 incompatible schema for events_daily partition", index: "pipeline-logs-*" },
  { timestamp: mins2(1320), level: "INFO", service: "pipeline-service", connectorId: "conn_salesforce_001", message: "Salesforce incremental sync \u2014 98,200 rows", index: "pipeline-logs-*" },
  { timestamp: mins2(1560), level: "WARN", service: "api-gateway", connectorId: "conn_postgres_001", message: "Connection pool saturation \u2014 92% utilization", index: "pipeline-logs-*" },
  { timestamp: mins2(1800), level: "INFO", service: "billing-service", message: "Weekly usage rollup completed", index: "pipeline-logs-*" },
  { timestamp: mins2(2100), level: "ERROR", service: "pipeline-service", connectorId: "conn_ga4_001", message: "GA4 export quota warning \u2014 approaching daily limit", index: "pipeline-logs-*" },
  { timestamp: mins2(2400), level: "INFO", service: "pipeline-service", connectorId: "conn_zendesk_001", message: "Zendesk full sync completed in 38m", index: "pipeline-logs-*" },
  { timestamp: mins2(2880), level: "WARN", service: "pipeline-service", connectorId: "conn_marketo_001", message: "Marketo connector scheduled pause initiated by operator", index: "pipeline-logs-*" },
  { timestamp: mins2(3300), level: "INFO", service: "api-gateway", message: "Certificate rotation completed for internal services", index: "pipeline-logs-*" },
  { timestamp: mins2(3600), level: "ERROR", service: "pipeline-service", connectorId: "conn_shopify_001", message: "Shopify API 503 \u2014 transient outage, sync deferred", index: "pipeline-logs-*" }
];
function resolveTimeWindow(opts) {
  let endMs = opts.endTime ? new Date(opts.endTime).getTime() : Date.now();
  let startMs;
  if (opts.startTime) {
    startMs = new Date(opts.startTime).getTime();
  } else {
    const hours = Math.min(Math.max(opts.timeRangeHours ?? 24, 1), 168);
    startMs = endMs - hours * 60 * 60 * 1e3;
  }
  if (startMs > endMs) {
    const tmp = startMs;
    startMs = endMs;
    endMs = tmp;
  }
  const timeRangeHours = Math.max(1, Math.round((endMs - startMs) / (60 * 60 * 1e3)));
  const label = opts.startTime && opts.endTime ? `${new Date(startMs).toLocaleDateString()} \u2013 ${new Date(endMs).toLocaleDateString()}` : `Last ${timeRangeHours}h`;
  return { startMs, endMs, timeRangeHours, label };
}
function filterLogsInWindow(index, window) {
  return syntheticLogs.filter((log) => {
    const t = new Date(log.timestamp).getTime();
    const matchesIndex = log.index === index || index.includes("*");
    return t >= window.startMs && t <= window.endMs && matchesIndex;
  });
}
function searchLogs(query, index = "pipeline-logs-*", opts = {}) {
  const window = resolveTimeWindow(opts);
  const q = query.toLowerCase();
  const hits = filterLogsInWindow(index, window).filter((log) => {
    if (!q) return true;
    return log.message.toLowerCase().includes(q) || log.level.toLowerCase().includes(q) || log.service.toLowerCase().includes(q) || (log.connectorId?.toLowerCase().includes(q) ?? false);
  });
  return {
    query,
    index,
    timeRangeHours: window.timeRangeHours,
    startTime: new Date(window.startMs).toISOString(),
    endTime: new Date(window.endMs).toISOString(),
    timeLabel: window.label,
    total: hits.length,
    hits: hits.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
  };
}
function buildHourlyBuckets(window) {
  const bucketCount = Math.min(24, window.timeRangeHours);
  const bucketSizeHours = window.timeRangeHours / bucketCount;
  const buckets = [];
  for (let i = bucketCount - 1; i >= 0; i--) {
    const bucketEnd = window.endMs - i * bucketSizeHours * 60 * 60 * 1e3;
    const bucketStart = bucketEnd - bucketSizeHours * 60 * 60 * 1e3;
    const logsInBucket = syntheticLogs.filter((log) => {
      const t = new Date(log.timestamp).getTime();
      return t >= bucketStart && t < bucketEnd;
    });
    const errors = logsInBucket.filter((l) => l.level === "ERROR").length;
    const events = Math.max(logsInBucket.length * 95, errors * 12 + 40);
    const hoursAgo = Math.round((window.endMs - bucketEnd) / (60 * 60 * 1e3));
    const label = bucketSizeHours >= 24 ? new Date(bucketStart).toLocaleDateString(void 0, { month: "short", day: "numeric" }) : hoursAgo === 0 ? "now" : `${hoursAgo}h`;
    buckets.push({ hour: i, label, events, errors });
  }
  return buckets;
}
function getErrorRate(index = "pipeline-logs-*", opts = {}) {
  const window = resolveTimeWindow(opts);
  const logs = filterLogsInWindow(index, window);
  const errorCount = logs.filter((l) => l.level === "ERROR").length;
  const totalEvents = Math.max(Math.round(logs.length * 95 + 400), errorCount * 10, 100);
  const errorRatePercent = Math.round(errorCount / totalEvents * 1e3) / 10;
  return {
    index,
    timeRangeHours: window.timeRangeHours,
    startTime: new Date(window.startMs).toISOString(),
    endTime: new Date(window.endMs).toISOString(),
    timeLabel: window.label,
    totalEvents,
    errorCount,
    errorRate: errorCount / totalEvents,
    errorRatePercent,
    trend: "stable",
    summary: `${errorRatePercent}% error rate (${errorCount}/${totalEvents} events) over ${window.label} \u2014 primarily GA4 schema failures and Zendesk latency`,
    hourlyBuckets: buildHourlyBuckets(window)
  };
}
function findCorrelatedErrors(connectorId, opts = {}) {
  const window = resolveTimeWindow(opts);
  const { hits } = searchLogs(connectorId, "pipeline-logs-*", opts);
  const errors = hits.filter((h) => h.level === "ERROR");
  const pattern = connectorId.includes("ga4") ? "schema_drift" : connectorId.includes("zendesk") ? "latency_degradation" : connectorId.includes("shopify") ? "partial_sync" : "general_failure";
  return {
    connectorId,
    timeRangeHours: window.timeRangeHours,
    correlationScore: errors.length > 0 ? Math.min(0.98, 0.88 + errors.length * 0.02) : 0.3,
    pattern,
    relatedErrors: errors,
    recommendation: `Review get_connector_logs for ${connectorId} and run check_freshness on downstream tables`
  };
}

// src/routes/elastic.ts
var router2 = (0, import_express2.Router)();
function timeOpts(body) {
  return {
    timeRangeHours: body.timeRangeHours,
    startTime: body.startTime,
    endTime: body.endTime
  };
}
router2.post("/search-logs", (req, res) => {
  const { query, index, timeRangeHours, startTime, endTime } = req.body;
  res.json(
    searchLogs(query ?? "", index ?? "pipeline-logs-*", timeOpts({ timeRangeHours, startTime, endTime }))
  );
});
router2.post("/get-error-rate", (req, res) => {
  const { index, timeRangeHours, startTime, endTime } = req.body;
  res.json(
    getErrorRate(index ?? "pipeline-logs-*", timeOpts({ timeRangeHours, startTime, endTime }))
  );
});
router2.post("/find-correlated-errors", (req, res) => {
  const { connectorId, timeRangeHours, startTime, endTime } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(
    findCorrelatedErrors(connectorId, timeOpts({ timeRangeHours, startTime, endTime }))
  );
});
var elastic_default = router2;

// src/routes/mongo.ts
var import_express3 = require("express");

// src/services/mongoService.ts
var incidents = [
  {
    id: "inc_001",
    title: "Sales dashboard broken (GA4 schema change)",
    summary: "Executive sales dashboard showing stale data. GA4 connector failed 5h ago due to new custom_dimension_12 column. Revenue attribution off by ~12%.",
    severity: "critical",
    status: "open",
    connectorId: "conn_ga4_001",
    incidentType: "schema_change",
    rootCause: "GA4 property added event_params.custom_dimension_12; Fivetran destination schema not reconciled.",
    recommendedActions: [
      "Run update_connector_schema for conn_ga4_001",
      "Trigger manual sync and verify analytics.ga4_events_daily freshness",
      "Notify analytics-team and pause dependent Looker dashboards"
    ],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1e3).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1e3).toISOString()
  },
  {
    id: "inc_002",
    title: "Customer support reporting delayed (Zendesk slow sync)",
    summary: "Support overview dashboard 95 minutes behind. Zendesk connector sync took 47m vs 30m SLA. CS managers reporting incomplete ticket counts.",
    severity: "high",
    status: "investigating",
    connectorId: "conn_zendesk_001",
    incidentType: "performance",
    rootCause: "Zendesk API pagination timeout under high ticket volume; partial batch commits.",
    recommendedActions: [
      "Increase sync parallelism or extend sync window",
      "Monitor conn_zendesk_001 next 3 sync cycles",
      "Consider temporary cache layer for support metrics"
    ],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1e3).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1e3).toISOString()
  },
  {
    id: "inc_003",
    title: "Marketing attribution data late (Marketo paused)",
    summary: "Marketo connector paused during maintenance. Campaign attribution models missing 24h of lead activity data.",
    severity: "medium",
    status: "resolved",
    connectorId: "conn_marketo_001",
    incidentType: "operational",
    rootCause: "Connector manually paused for schema migration \u2014 not resumed after maintenance window.",
    recommendedActions: [
      "Resume conn_marketo_001 and trigger backfill sync",
      "Validate marketing.marketo_leads freshness"
    ],
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1e3).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1e3).toISOString()
  },
  {
    id: "inc_004",
    title: "Revenue report missing yesterday's orders (Shopify partial sync)",
    summary: "Finance daily revenue report missing 450 Shopify orders from yesterday. Partial sync due to API rate limiting.",
    severity: "high",
    status: "open",
    connectorId: "conn_shopify_001",
    incidentType: "partial_sync",
    rootCause: "Shopify REST API 429 rate limits during peak order window; 450 rows deferred.",
    recommendedActions: [
      "Trigger manual sync for conn_shopify_001",
      "Verify commerce.shopify_orders row counts vs source",
      "Schedule off-peak sync window to avoid rate limits"
    ],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1e3).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1e3).toISOString()
  }
];
var playbooks = {
  schema_change: {
    incidentType: "schema_change",
    title: "Schema Change Incident Playbook",
    steps: [
      { order: 1, action: "Identify drift", details: "Use get_connector_logs and search_logs to confirm new columns." },
      { order: 2, action: "Assess impact", details: "Run check_freshness and check_impact on affected BigQuery tables." },
      { order: 3, action: "Remediate", details: "Call update_connector_schema, then trigger_sync." },
      { order: 4, action: "Verify & close", details: "Confirm error rate drops and freshness returns to OK." }
    ]
  },
  performance: {
    incidentType: "performance",
    title: "Pipeline Performance Playbook",
    steps: [
      { order: 1, action: "Baseline", details: "Compare sync duration against 7-day average." },
      { order: 2, action: "Isolate", details: "Check connector logs for throttling or API rate limits." },
      { order: 3, action: "Mitigate", details: "Reschedule sync window or increase parallelism." }
    ]
  },
  partial_sync: {
    incidentType: "partial_sync",
    title: "Partial Sync Playbook",
    steps: [
      { order: 1, action: "Quantify gap", details: "Compare source row counts vs destination." },
      { order: 2, action: "Retry", details: "Trigger manual sync during off-peak hours." },
      { order: 3, action: "Validate", details: "Run check_freshness and notify downstream consumers." }
    ]
  },
  operational: {
    incidentType: "operational",
    title: "Operational Pause Playbook",
    steps: [
      { order: 1, action: "Confirm intent", details: "Verify pause was intentional vs accidental." },
      { order: 2, action: "Resume", details: "Resume connector and trigger backfill if needed." }
    ]
  }
};
var nextId = 5;
function createIncident(payload) {
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const incident = {
    id: `inc_${String(nextId++).padStart(3, "0")}`,
    ...payload,
    status: "open",
    createdAt: now,
    updatedAt: now
  };
  incidents.push(incident);
  return { id: incident.id, incident };
}
function listIncidents(filters) {
  return incidents.filter((inc) => {
    if (filters?.status && inc.status !== filters.status) return false;
    if (filters?.severity && inc.severity !== filters.severity) return false;
    if (filters?.connectorId && inc.connectorId !== filters.connectorId) return false;
    return true;
  });
}
function updateIncident(id, updates) {
  const idx = incidents.findIndex((i) => i.id === id);
  if (idx === -1) return { success: false, message: "Incident not found" };
  incidents[idx] = {
    ...incidents[idx],
    ...updates,
    id: incidents[idx].id,
    updatedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
  return { success: true, incident: incidents[idx] };
}
function getPlaybook(incidentType) {
  return playbooks[incidentType] ?? {
    incidentType,
    title: "Generic Incident Playbook",
    steps: [
      { order: 1, action: "Triage", details: "Gather logs and connector status." },
      { order: 2, action: "Mitigate", details: "Apply fix or escalate to on-call." }
    ]
  };
}

// src/routes/mongo.ts
var router3 = (0, import_express3.Router)();
router3.post("/create-incident", (req, res) => {
  const { title, summary, severity, connectorId, incidentType } = req.body;
  if (!title || !summary || !severity || !incidentType) {
    res.status(400).json({ error: "title, summary, severity, and incidentType are required" });
    return;
  }
  res.status(201).json(
    createIncident({ title, summary, severity, connectorId, incidentType })
  );
});
router3.get("/list-incidents", (req, res) => {
  const filters = {};
  if (req.query.status) filters.status = req.query.status;
  if (req.query.severity) filters.severity = req.query.severity;
  if (req.query.connectorId) filters.connectorId = String(req.query.connectorId);
  res.json({ incidents: listIncidents(filters) });
});
router3.put("/update-incident/:id", (req, res) => {
  const result = updateIncident(req.params.id, req.body);
  if (!result.success) {
    res.status(404).json(result);
    return;
  }
  res.json(result);
});
router3.post("/get-playbook", (req, res) => {
  const { incidentType } = req.body;
  if (!incidentType) {
    res.status(400).json({ error: "incidentType is required" });
    return;
  }
  res.json({ playbook: getPlaybook(incidentType) });
});
var mongo_default = router3;

// src/routes/bigquery.ts
var import_express4 = require("express");

// src/services/bigqueryService.ts
var demoFreshness = {
  "analytics.ga4_events_daily": {
    lastTimestamp: new Date(Date.now() - 300 * 60 * 1e3).toISOString(),
    freshnessMinutes: 300,
    status: "CRITICAL"
  },
  "analytics.ga4_events_intraday": {
    lastTimestamp: new Date(Date.now() - 180 * 60 * 1e3).toISOString(),
    freshnessMinutes: 180,
    status: "LATE"
  },
  "crm.salesforce_accounts": {
    lastTimestamp: new Date(Date.now() - 10 * 60 * 1e3).toISOString(),
    freshnessMinutes: 10,
    status: "OK"
  },
  "commerce.shopify_orders": {
    lastTimestamp: new Date(Date.now() - 40 * 60 * 1e3).toISOString(),
    freshnessMinutes: 40,
    status: "LATE"
  },
  "marketing.marketo_leads": {
    lastTimestamp: new Date(Date.now() - 1440 * 60 * 1e3).toISOString(),
    freshnessMinutes: 1440,
    status: "CRITICAL"
  },
  "support.zendesk_tickets": {
    lastTimestamp: new Date(Date.now() - 95 * 60 * 1e3).toISOString(),
    freshnessMinutes: 95,
    status: "LATE"
  },
  "warehouse.postgres_orders": {
    lastTimestamp: new Date(Date.now() - 12 * 60 * 1e3).toISOString(),
    freshnessMinutes: 12,
    status: "OK"
  }
};
var impactByTable = {
  ga4_events_daily: {
    views: [
      { name: "demo-analytics-prod.analytics.sales_dashboard", type: "view", owner: "sales-team" },
      { name: "demo-analytics-prod.analytics.marketing_funnel", type: "view", owner: "growth-team" },
      { name: "demo-analytics-prod.analytics.executive_kpis", type: "view", owner: "exec-team" }
    ],
    dashboards: ["Executive KPI Dashboard", "Sales Performance", "Marketing Attribution"]
  },
  shopify_orders: {
    views: [
      { name: "demo-analytics-prod.analytics.revenue_daily", type: "view", owner: "finance-team" },
      { name: "demo-analytics-prod.analytics.order_funnel", type: "view", owner: "growth-team" }
    ],
    dashboards: ["Finance Daily Revenue", "E-commerce Overview"]
  },
  zendesk_tickets: {
    views: [
      { name: "demo-analytics-prod.analytics.support_overview", type: "view", owner: "support-team" },
      { name: "demo-analytics-prod.analytics.csat_metrics", type: "view", owner: "support-team" }
    ],
    dashboards: ["Customer Support Overview", "CSAT Tracker"]
  },
  salesforce_accounts: {
    views: [
      { name: "demo-analytics-prod.analytics.crm_pipeline", type: "view", owner: "sales-ops" }
    ],
    dashboards: ["CRM Pipeline Dashboard"]
  }
};
function checkFreshness(tables) {
  const results = tables.map((table) => {
    const demo = demoFreshness[table];
    if (demo) return { table, ...demo };
    return {
      table,
      lastTimestamp: new Date(Date.now() - 60 * 60 * 1e3).toISOString(),
      freshnessMinutes: 60,
      status: "OK"
    };
  });
  const breached = results.filter((r) => r.status !== "OK").length;
  return {
    checkedAt: (/* @__PURE__ */ new Date()).toISOString(),
    tables: results,
    summary: breached > 0 ? `${breached} table(s) breaching freshness SLA \u2014 GA4 and support tables most affected` : "All tables within freshness SLA"
  };
}
function checkImpact(projectId, datasetId, tableId) {
  const fullTable = `${projectId}.${datasetId}.${tableId}`;
  const impact = impactByTable[tableId] ?? {
    views: [
      { name: `${projectId}.${datasetId}.${tableId}_summary`, type: "view", owner: "analytics-team" }
    ],
    dashboards: ["General Analytics Dashboard"]
  };
  const viewCount = impact.views.length;
  const dashCount = impact.dashboards.length;
  const downstreamViewNames = impact.views.map((v) => v.name);
  return {
    upstream_table: fullTable,
    table: fullTable,
    downstream_views: downstreamViewNames,
    downstreamViews: impact.views,
    affectedDashboards: impact.dashboards,
    summary: `Stale data in ${fullTable} impacts ${viewCount} downstream view(s) and ${dashCount} dashboard(s): ${impact.dashboards.join(", ")}. Estimated business impact: delayed reporting for dependent teams.`
  };
}
function checkImpactForConnectorTable(primaryTable) {
  const parts = primaryTable.split(".");
  if (parts.length >= 3) {
    const [project, dataset, table] = parts;
    return checkImpact(project, dataset, table);
  }
  return checkImpact("demo-analytics-prod", "analytics", primaryTable.replace(/^.*\./, ""));
}

// src/routes/bigquery.ts
var router4 = (0, import_express4.Router)();
router4.post("/check-freshness", (req, res) => {
  const { tables } = req.body;
  if (!tables?.length) {
    res.status(400).json({ error: "tables array is required" });
    return;
  }
  res.json(checkFreshness(tables));
});
router4.post("/check-impact", (req, res) => {
  const { project_id, dataset_id, table_id, primaryTable } = req.body;
  if (primaryTable) {
    res.json(checkImpactForConnectorTable(primaryTable));
    return;
  }
  if (!project_id || !dataset_id || !table_id) {
    res.status(400).json({ error: "project_id, dataset_id, and table_id are required (or primaryTable)" });
    return;
  }
  res.json(checkImpact(project_id, dataset_id, table_id));
});
var bigquery_default = router4;

// src/routes/chat.ts
var import_express5 = require("express");

// src/services/intelligenceService.ts
var WATCHED_TABLES = [
  "analytics.ga4_events_daily",
  "analytics.ga4_events_intraday",
  "crm.salesforce_accounts",
  "commerce.shopify_orders",
  "support.zendesk_tickets",
  "marketing.marketo_leads"
];
function gradeFromScore(score) {
  if (score >= 90) return "A";
  if (score >= 75) return "B";
  if (score >= 60) return "C";
  if (score >= 45) return "D";
  return "F";
}
function connectorHealthPoints(status) {
  const map = {
    active: 100,
    syncing: 85,
    warning: 45,
    paused: 60,
    failed: 15
  };
  return map[status] ?? 50;
}
function freshnessHealthPoints(status) {
  const map = { OK: 100, LATE: 50, CRITICAL: 18 };
  return map[status] ?? 50;
}
function computeCompositeScore(connectors, freshnessTables, activeIncidents, errorRatePercent) {
  const connectorScore = Math.round(
    connectors.reduce((sum, c) => sum + connectorHealthPoints(c.status), 0) / connectors.length
  );
  const freshnessScore = Math.round(
    freshnessTables.reduce((sum, t) => sum + freshnessHealthPoints(t.status), 0) / freshnessTables.length
  );
  let incidentScore = 100;
  for (const inc of activeIncidents) {
    if (inc.severity === "critical") incidentScore -= 32;
    else if (inc.severity === "high") incidentScore -= 18;
    else if (inc.severity === "medium") incidentScore -= 10;
    else incidentScore -= 4;
  }
  incidentScore = Math.max(15, incidentScore);
  let observabilityScore = 100;
  if (errorRatePercent > 10) observabilityScore = 45;
  else if (errorRatePercent > 5) observabilityScore = 78;
  else if (errorRatePercent > 2) observabilityScore = 92;
  const raw2 = connectorScore * 0.35 + freshnessScore * 0.32 + incidentScore * 0.2 + observabilityScore * 0.13;
  return Math.max(18, Math.min(100, Math.round(raw2)));
}
function timedTrace(tool, endpoint, summary, status = "ok", baseMs = 30) {
  return {
    tool,
    endpoint,
    durationMs: baseMs + Math.floor(Math.random() * 80),
    status,
    summary
  };
}
function runReliabilityScan() {
  const trace = [];
  const connectors = listConnectors();
  trace.push(
    timedTrace(
      "list_connectors",
      "/api/fivetran/list-connectors",
      `${connectors.length} connectors \u2014 ${connectors.filter((c) => c.status === "failed").length} failed`,
      connectors.some((c) => c.status === "failed") ? "warn" : "ok"
    )
  );
  const failed = connectors.find((c) => c.status === "failed");
  if (failed) {
    const logs = getConnectorLogs(failed.id, 24);
    trace.push(
      timedTrace(
        "get_connector_logs",
        "/api/fivetran/get-connector-logs",
        `${logs.count} log entries for ${failed.id}`,
        "warn"
      )
    );
    const correlated = findCorrelatedErrors(failed.id, { timeRangeHours: 24 });
    trace.push(
      timedTrace(
        "find_correlated_errors",
        "/api/elastic/find-correlated-errors",
        `Pattern: ${correlated.pattern} (${Math.round(correlated.correlationScore * 100)}% confidence)`,
        "warn"
      )
    );
  }
  const errorRate = getErrorRate("pipeline-logs-*", { timeRangeHours: 24 });
  trace.push(
    timedTrace(
      "get_error_rate",
      "/api/elastic/get-error-rate",
      `${errorRate.errorRatePercent}% error rate (${errorRate.errorCount}/${errorRate.totalEvents} events)`,
      errorRate.errorRatePercent > 10 ? "warn" : "ok"
    )
  );
  const freshness = checkFreshness(WATCHED_TABLES);
  trace.push(
    timedTrace(
      "check_freshness",
      "/api/bigquery/check-freshness",
      freshness.summary,
      freshness.tables.some((t) => t.status === "CRITICAL") ? "error" : "warn"
    )
  );
  const activeIncidents = listIncidents().filter((inc) => inc.status !== "resolved");
  trace.push(
    timedTrace(
      "list_incidents",
      "/api/mongo/list-incidents",
      `${activeIncidents.length} active incident(s)`,
      activeIncidents.length > 0 ? "warn" : "ok"
    )
  );
  const findings = [];
  for (const c of connectors) {
    if (c.status === "failed") {
      findings.push({
        severity: "critical",
        category: "Pipeline",
        message: `${c.name} is FAILED: ${c.errorMessage ?? "sync failure"}`,
        suggestedAction: "Run autonomous remediation or update_connector_schema"
      });
    } else if (c.status === "warning") {
      findings.push({
        severity: "high",
        category: "Pipeline",
        message: `${c.name} degraded: ${c.errorMessage ?? "performance issue"}`
      });
    }
  }
  for (const t of freshness.tables) {
    if (t.status === "CRITICAL") {
      findings.push({
        severity: "critical",
        category: "Freshness",
        message: `${t.table} is ${t.freshnessMinutes}min stale (CRITICAL)`,
        suggestedAction: "Resolve upstream connector and verify check_freshness"
      });
    } else if (t.status === "LATE") {
      findings.push({
        severity: "high",
        category: "Freshness",
        message: `${t.table} breaching SLA (${t.freshnessMinutes}min late)`
      });
    }
  }
  if (errorRate.errorRatePercent > 10) {
    findings.push({
      severity: "high",
      category: "Observability",
      message: `Error rate elevated at ${errorRate.errorRatePercent}% over 24h`,
      suggestedAction: "search_logs for correlated schema errors"
    });
  }
  for (const inc of activeIncidents) {
    findings.push({
      severity: inc.severity === "critical" ? "critical" : inc.severity === "high" ? "high" : "medium",
      category: "Incident",
      message: `[${inc.id}] ${inc.title}`,
      suggestedAction: inc.recommendedActions?.[0]
    });
  }
  const score = computeCompositeScore(
    connectors,
    freshness.tables,
    activeIncidents,
    errorRate.errorRatePercent
  );
  return {
    score,
    grade: gradeFromScore(score),
    trend: score < 70 ? "declining" : "stable",
    scannedAt: (/* @__PURE__ */ new Date()).toISOString(),
    findings: findings.sort((a, b) => {
      const order = { critical: 0, high: 1, medium: 2, low: 3 };
      return order[a.severity] - order[b.severity];
    }),
    toolTrace: trace,
    summary: score >= 80 ? "Platform reliability is within acceptable bounds with minor issues to monitor." : score >= 60 ? "Multiple reliability signals degraded \u2014 agent-recommended remediation advised." : "Critical reliability breach detected \u2014 immediate autonomous or manual intervention required."
  };
}
function predictSlaBreaches() {
  const freshness = checkFreshness(WATCHED_TABLES);
  const connectors = listConnectors();
  const hasFailedPipeline = connectors.some((c) => c.status === "failed");
  return freshness.tables.map((t) => {
    const velocityMinPerHour = t.status === "CRITICAL" ? 45 : t.status === "LATE" ? 22 : 5;
    const slaMinutes = 120;
    const minutesToBreach = Math.max(0, slaMinutes - t.freshnessMinutes);
    const breachProbability = t.status === "CRITICAL" ? 0.94 : t.status === "LATE" ? 0.72 : hasFailedPipeline && t.table.includes("analytics") ? 0.38 : 0.08;
    return {
      table: t.table,
      currentFreshnessMinutes: t.freshnessMinutes,
      status: t.status,
      slaMinutes,
      predictedBreachInMinutes: minutesToBreach,
      breachProbability: Math.round(breachProbability * 100),
      riskLevel: breachProbability > 0.8 ? "critical" : breachProbability > 0.5 ? "high" : breachProbability > 0.25 ? "medium" : "low",
      recommendation: breachProbability > 0.5 ? "Prioritize connector remediation \u2014 SLA breach imminent" : "Within SLA \u2014 continue monitoring"
    };
  });
}
function getLineageGraph() {
  return {
    nodes: [
      { id: "conn_ga4_001", type: "connector", label: "GA4 \u2192 BigQuery", status: "failed", x: 80, y: 120 },
      { id: "conn_salesforce_001", type: "connector", label: "Salesforce \u2192 BQ", status: "active", x: 80, y: 280 },
      { id: "events_intraday", type: "table", label: "events_intraday", status: "LATE", x: 280, y: 80 },
      { id: "events_daily", type: "table", label: "events_daily", status: "CRITICAL", x: 280, y: 160 },
      { id: "sf_accounts", type: "table", label: "salesforce_accounts", status: "OK", x: 280, y: 260 },
      { id: "dau_view", type: "view", label: "daily_active_users", status: "STALE", x: 480, y: 100 },
      { id: "funnel_view", type: "view", label: "funnel_conversion", status: "STALE", x: 480, y: 180 },
      { id: "exec_dash", type: "dashboard", label: "Executive KPIs", status: "IMPACTED", x: 680, y: 120 },
      { id: "ml_features", type: "table", label: "feature_store_events", status: "STALE", x: 480, y: 240 }
    ],
    edges: [
      { from: "conn_ga4_001", to: "events_intraday", label: "sync" },
      { from: "conn_ga4_001", to: "events_daily", label: "sync" },
      { from: "conn_salesforce_001", to: "sf_accounts", label: "sync" },
      { from: "events_intraday", to: "dau_view", label: "feeds" },
      { from: "events_daily", to: "funnel_view", label: "feeds" },
      { from: "events_daily", to: "ml_features", label: "feeds" },
      { from: "dau_view", to: "exec_dash", label: "powers" },
      { from: "funnel_view", to: "exec_dash", label: "powers" }
    ],
    blastRadius: {
      rootCause: "conn_ga4_001 schema drift",
      affectedAssets: 5,
      impactedDashboards: 2,
      estimatedBusinessImpact: "Executive reporting 4h stale; ML features degraded"
    }
  };
}
function runAutoRemediate(connectorId) {
  const connector = listConnectors().find((c) => c.id === connectorId);
  if (!connector) {
    return { success: false, connectorId, steps: [], message: "Connector not found" };
  }
  const steps = [];
  steps.push({
    step: 1,
    tool: "get_connector_logs",
    endpoint: "/api/fivetran/get-connector-logs",
    status: "completed",
    message: "Confirmed schema drift: custom_dimension_12 missing in destination",
    durationMs: 48
  });
  steps.push({
    step: 2,
    tool: "update_connector_schema",
    endpoint: "/api/fivetran/update-connector-schema",
    status: "completed",
    message: "Applied schema patch \u2014 added event_params.custom_dimension_12",
    durationMs: 120
  });
  updateConnectorSchema(connectorId, {
    columns: { events: ["event_params.custom_dimension_12"] },
    mode: "append"
  });
  steps.push({
    step: 3,
    tool: "trigger_sync",
    endpoint: "/api/fivetran/trigger-sync",
    status: "completed",
    message: "Manual sync triggered \u2014 estimated 12 min",
    durationMs: 65
  });
  triggerSync(connectorId);
  steps.push({
    step: 4,
    tool: "check_freshness",
    endpoint: "/api/bigquery/check-freshness",
    status: "completed",
    message: "Post-remediation freshness check queued \u2014 expect recovery within 1 sync cycle",
    durationMs: 38
  });
  steps.push({
    step: 5,
    tool: "create_incident",
    endpoint: "/api/mongo/create-incident",
    status: "completed",
    message: "Auto-documented remediation in incident timeline (demo)",
    durationMs: 22
  });
  return {
    success: true,
    connectorId,
    connectorName: connector.name,
    mode: "autonomous",
    completedAt: (/* @__PURE__ */ new Date()).toISOString(),
    steps,
    message: "Autonomous remediation sequence completed. Connector schema updated and sync triggered. Monitor freshness over next cycle."
  };
}
var TOOL_PATTERNS = [
  {
    pattern: /connector|pipeline|fivetran|sync|list/i,
    tools: ["list_connectors", "get_connector_status", "get_connector_history"]
  },
  { pattern: /log|error|exception|search|elastic/i, tools: ["search_logs", "get_error_rate"] },
  { pattern: /incident|sev|ticket|playbook/i, tools: ["list_incidents", "create_incident", "get_playbook"] },
  {
    pattern: /fresh|stale|sla|bigquery|table|impact|dashboard|downstream/i,
    tools: ["check_freshness", "check_impact", "get_schema_changes"]
  },
  {
    pattern: /scan|reliability|health|audit|full|trend|duration/i,
    tools: ["list_connectors", "get_connector_history", "check_freshness", "search_logs", "list_incidents"]
  },
  {
    pattern: /fix|remediat|repair|schema|update|drift|column/i,
    tools: ["get_connector_logs", "get_schema_changes", "check_impact", "update_connector_schema", "trigger_sync"]
  },
  {
    pattern: /cost|usage|mar|credit|expensive|billing/i,
    tools: ["usage_summary", "list_connectors", "check_impact"]
  }
];
function inferToolTrace(message) {
  const matched = /* @__PURE__ */ new Set();
  for (const { pattern, tools } of TOOL_PATTERNS) {
    if (pattern.test(message)) {
      tools.forEach((t) => matched.add(t));
    }
  }
  if (matched.size === 0) {
    matched.add("list_connectors");
    matched.add("search_logs");
  }
  const endpointMap = {
    list_connectors: "/api/fivetran/list-connectors",
    get_connector_status: "/api/fivetran/get-connector-status",
    get_connector_logs: "/api/fivetran/get-connector-logs",
    get_connector_history: "/api/fivetran/get-connector-history",
    get_schema_changes: "/api/fivetran/get-schema-changes",
    usage_summary: "/api/fivetran/usage-summary",
    trigger_sync: "/api/fivetran/trigger-sync",
    update_connector_schema: "/api/fivetran/update-connector-schema",
    search_logs: "/api/elastic/search-logs",
    get_error_rate: "/api/elastic/get-error-rate",
    create_incident: "/api/mongo/create-incident",
    list_incidents: "/api/mongo/list-incidents",
    get_playbook: "/api/mongo/get-playbook",
    check_freshness: "/api/bigquery/check-freshness",
    check_impact: "/api/bigquery/check-impact"
  };
  return Array.from(matched).map(
    (tool, i) => timedTrace(tool, endpointMap[tool] ?? `/api/${tool}`, `Agent invoked ${tool}`, "ok", 40 + i * 15)
  );
}
var eventCounter = 0;
var EVENT_TEMPLATES = [
  { type: "sync", severity: "info", message: "Salesforce \u2192 BigQuery sync heartbeat OK" },
  { type: "alert", severity: "warn", message: "Freshness drift detected on analytics.events_intraday" },
  { type: "error", severity: "error", message: "GA4 connector: schema mismatch retry 2/3" },
  { type: "agent", severity: "info", message: "SRE Agent correlated 3 errors to conn_ga4_001" },
  { type: "sla", severity: "warn", message: "Predicted SLA breach for events_daily in ~45 min" },
  { type: "incident", severity: "warn", message: "Incident inc_001 escalated \u2014 no owner assigned" }
];
function getLiveEvents(since) {
  const now = Date.now();
  const sinceMs = since ? new Date(since).getTime() : now - 6e4;
  const events = [];
  for (let i = 0; i < 3; i++) {
    const tpl = EVENT_TEMPLATES[(eventCounter + i) % EVENT_TEMPLATES.length];
    events.push({
      id: `evt_${++eventCounter}_${Date.now()}`,
      timestamp: new Date(now - i * 8e3).toISOString(),
      type: tpl.type,
      severity: tpl.severity,
      message: tpl.message,
      source: tpl.type === "agent" ? "aroa-agent" : "pipeline-monitor"
    });
  }
  return {
    events: events.filter((e) => new Date(e.timestamp).getTime() > sinceMs),
    serverTime: (/* @__PURE__ */ new Date()).toISOString()
  };
}

// src/services/agentService.ts
var GROUNDING_SOURCES = [
  {
    id: "fivetran",
    name: "Fivetran Control Plane",
    tools: ["list_connectors", "get_connector_history", "get_schema_changes", "usage_summary"],
    endpointPrefix: "/api/fivetran"
  },
  {
    id: "elastic",
    name: "Elastic Observability",
    tools: ["search_logs", "get_error_rate", "find_correlated_errors"],
    endpointPrefix: "/api/elastic"
  },
  {
    id: "mongo",
    name: "Incident Management",
    tools: ["list_incidents", "create_incident", "get_playbook"],
    endpointPrefix: "/api/mongo"
  },
  {
    id: "bigquery",
    name: "BigQuery Lineage & Freshness",
    tools: ["check_freshness", "check_impact"],
    endpointPrefix: "/api/bigquery"
  },
  {
    id: "intelligence",
    name: "AROA Intelligence Engine",
    tools: ["reliability_scan", "sla_predictions", "lineage_graph", "auto_remediate"],
    endpointPrefix: "/api/intelligence"
  }
];
function getAgentStatus() {
  const live = config.GEMINI_API_KEY !== "your_gemini_api_key" && config.AGENT_ID !== "agents/YOUR_AGENT_ID";
  return {
    connected: live,
    mode: live ? "agent_builder" : "demo",
    agentId: maskAgentId(config.AGENT_ID),
    apiRevision: "2026-05-20",
    modelFamily: "Gemini 2.5",
    interactionsApi: "generativelanguage.googleapis.com/v1beta/interactions",
    sessionContinuity: true,
    toolCalling: true,
    groundingSourceCount: GROUNDING_SOURCES.length,
    groundingSources: GROUNDING_SOURCES.map((s) => ({
      id: s.id,
      name: s.name,
      toolCount: s.tools.length
    })),
    capabilities: [
      "Multi-turn session memory (previous_interaction_id)",
      "Autonomous tool orchestration",
      "Grounded reliability & pipeline context",
      "Schema drift + blast radius reasoning",
      "Cost-aware MAR recommendations",
      "Executive briefing synthesis"
    ]
  };
}
function maskAgentId(id) {
  if (id.length <= 12) return id;
  return `${id.slice(0, 10)}\u2026${id.slice(-4)}`;
}
function generateExecutiveBriefing() {
  const scan = runReliabilityScan();
  const lineage = getLineageGraph();
  const connectors = listConnectors();
  const usage = getUsageSummary();
  const incidents2 = listIncidents().filter((i) => i.status !== "resolved");
  const failed = connectors.filter((c) => c.status === "failed");
  const topMar = usage.usage[0];
  const criticalFindings = scan.findings.filter((f) => f.severity === "critical").slice(0, 3);
  const headline = scan.score < 60 ? "Critical reliability posture \u2014 immediate intervention required" : scan.score < 80 ? "Elevated risk \u2014 targeted remediation recommended" : "Platform stable with isolated degradation";
  const sections = [
    {
      title: "Situation",
      body: `Composite reliability score is ${scan.score}/100 (${scan.grade}). ${scan.summary}`,
      citations: ["reliability_scan", "list_connectors"]
    },
    {
      title: "Blast radius",
      body: `${lineage.blastRadius.rootCause} affects ${lineage.blastRadius.affectedAssets} downstream assets and ${lineage.blastRadius.impactedDashboards} executive dashboards. ${lineage.blastRadius.estimatedBusinessImpact}.`,
      citations: ["lineage_graph", "check_impact"]
    },
    {
      title: "Active incidents",
      body: incidents2.length === 0 ? "No open incidents." : `${incidents2.length} active incident(s): ${incidents2.map((i) => i.title).join("; ")}.`,
      citations: ["list_incidents"]
    },
    {
      title: "Cost & efficiency",
      body: `Highest MAR connector: ${topMar.connectorName} (${(topMar.marThisMonth / 1e6).toFixed(1)}M rows/mo, ${topMar.estCreditsThisMonth} est. credits). ${failed.length > 0 ? "Failed pipelines still incur sync overhead \u2014 prioritize schema reconciliation." : "Usage within expected bounds."}`,
      citations: ["usage_summary"]
    },
    {
      title: "Recommended actions",
      body: criticalFindings.length ? criticalFindings.map((f) => f.suggestedAction ?? f.message).join(" \xB7 ") : "Continue monitoring SLA predictions and error rate trends.",
      citations: ["reliability_scan", "sla_predictions"]
    }
  ];
  return {
    generatedAt: (/* @__PURE__ */ new Date()).toISOString(),
    agentMode: getAgentStatus().mode,
    headline,
    score: scan.score,
    grade: scan.grade,
    trend: scan.trend,
    sections,
    groundedIn: GROUNDING_SOURCES.map((s) => s.name),
    suggestedPrompts: [
      "Summarize blast radius for GA4 and list impacted dashboards",
      "Which connectors should we de-prioritize based on MAR vs downstream usage?",
      "Draft an incident update for the executive team",
      "Run autonomous remediation plan for conn_ga4_001"
    ]
  };
}
async function generateBriefingWithGemini() {
  const briefing = generateExecutiveBriefing();
  const live = getAgentStatus().connected;
  if (!live) {
    return briefing;
  }
  try {
    const prompt = `You are an enterprise SRE copilot. Produce a concise executive briefing (3 short paragraphs) based on:
Score: ${briefing.score}/100
Headline: ${briefing.headline}
Findings: ${briefing.sections.map((s) => s.title + ": " + s.body).join("\n")}`;
    const resp = await fetch("https://generativelanguage.googleapis.com/v1beta/interactions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": config.GEMINI_API_KEY,
        "Api-Revision": "2026-05-20"
      },
      body: JSON.stringify({
        agent: config.AGENT_ID,
        input: prompt
      })
    });
    if (resp.ok) {
      const data = await resp.json();
      if (data.output_text) {
        return {
          ...briefing,
          geminiNarrative: data.output_text
        };
      }
    }
  } catch {
  }
  return briefing;
}

// src/services/geminiService.ts
var INTERACTIONS_URL = "https://generativelanguage.googleapis.com/v1beta/interactions";
function buildAgentMeta(interactionId, mode = "demo") {
  const status = getAgentStatus();
  return {
    mode,
    interactionId,
    agentId: status.agentId,
    apiRevision: status.apiRevision,
    modelFamily: status.modelFamily,
    groundingSources: status.groundingSources,
    sessionContinuity: status.sessionContinuity
  };
}
function extractReply(data) {
  if (data.output_text) {
    return data.output_text;
  }
  if (data.steps?.length) {
    const texts = [];
    for (const step of data.steps) {
      if (step.type === "model_output" && step.content) {
        for (const part of step.content) {
          if (part.type === "text" && part.text) {
            texts.push(part.text);
          }
        }
      }
    }
    if (texts.length) {
      return texts.join("\n\n");
    }
  }
  return "No response text received from agent.";
}
async function chatWithAgent(message, sessionId) {
  if (config.GEMINI_API_KEY === "your_gemini_api_key" || config.AGENT_ID === "agents/YOUR_AGENT_ID") {
    return {
      reply: "\u26A0\uFE0F Demo mode: Set GEMINI_API_KEY and AGENT_ID in backend/.env to connect to your Agent Builder agent.\n\nMeanwhile, here is what I would investigate:\n\u2022 GA4 connector (conn_ga4_001) is FAILED \u2014 schema drift on custom_dimension_12\n\u2022 analytics.ga4_events_daily freshness is CRITICAL (300 min late)\n\u2022 GA4 has the highest MAR (~48M rows/mo) \u2014 consider lowering sync frequency if downstream usage is low\n\u2022 Impacted views: demo-analytics-prod.analytics.sales_dashboard, marketing_funnel\n\u2022 Recommend: get_schema_changes \u2192 check_impact \u2192 update_connector_schema \u2192 trigger_sync",
      interactionId: sessionId ?? `demo_${Date.now()}`,
      toolTrace: inferToolTrace(message),
      agentMeta: buildAgentMeta(sessionId, "demo")
    };
  }
  const body = {
    agent: config.AGENT_ID,
    input: message
  };
  if (sessionId) {
    body.previous_interaction_id = sessionId;
  }
  const resp = await fetch(INTERACTIONS_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": config.GEMINI_API_KEY,
      "Api-Revision": "2026-05-20"
    },
    body: JSON.stringify(body)
  });
  const data = await resp.json();
  if (!resp.ok) {
    const errMsg = data.error?.message ?? `Gemini API error (${resp.status})`;
    throw new Error(errMsg);
  }
  return {
    reply: extractReply(data),
    interactionId: data.id,
    toolTrace: inferToolTrace(message),
    agentMeta: buildAgentMeta(data.id, "live")
  };
}

// src/routes/chat.ts
var router5 = (0, import_express5.Router)();
router5.post("/", async (req, res, next) => {
  try {
    const { message, sessionId } = req.body;
    if (!message?.trim()) {
      res.status(400).json({ error: "message is required" });
      return;
    }
    const { reply, interactionId, toolTrace, agentMeta } = await chatWithAgent(
      message.trim(),
      sessionId
    );
    res.json({ reply, sessionId: interactionId, toolTrace, agentMeta });
  } catch (err) {
    next(err);
  }
});
var chat_default = router5;

// src/routes/intelligence.ts
var import_express6 = require("express");
var router6 = (0, import_express6.Router)();
router6.post("/reliability-scan", (_req, res) => {
  res.json(runReliabilityScan());
});
router6.get("/sla-predictions", (_req, res) => {
  res.json({ predictions: predictSlaBreaches() });
});
router6.get("/lineage-graph", (_req, res) => {
  res.json(getLineageGraph());
});
router6.post("/auto-remediate", (req, res) => {
  const { connectorId } = req.body;
  if (!connectorId) {
    res.status(400).json({ error: "connectorId is required" });
    return;
  }
  res.json(runAutoRemediate(connectorId));
});
router6.get("/live-events", (req, res) => {
  const since = req.query.since;
  res.json(getLiveEvents(since));
});
router6.get("/agent-status", (_req, res) => {
  res.json(getAgentStatus());
});
router6.post("/ai-briefing", async (_req, res, next) => {
  try {
    const briefing = await generateBriefingWithGemini();
    res.json(briefing);
  } catch (err) {
    next(err);
  }
});
var intelligence_default = router6;

// src/routes/ai.ts
var import_express7 = require("express");

// src/services/aiService.ts
var INTERACTIONS_URL2 = "https://generativelanguage.googleapis.com/v1beta/interactions";
var KEYWORD_PATTERNS = [
  {
    match: /shopify/i,
    build: (d) => ({
      id: `conn_shopify_${Date.now().toString(36).slice(-4)}`,
      name: "Shopify \u2192 BigQuery (AI Generated)",
      source: "Shopify",
      destination: "BigQuery",
      schedule: d.match(/daily/i) ? "every 24 hours" : "every 15 minutes",
      tables: ["orders", "order_items", "customers", "products"],
      notes: "Configured from natural language prompt. Excludes test orders. Sandbox project recommended."
    })
  },
  {
    match: /zendesk|support|ticket/i,
    build: () => ({
      id: `conn_zendesk_${Date.now().toString(36).slice(-4)}`,
      name: "Zendesk \u2192 BigQuery (Full History)",
      source: "Zendesk",
      destination: "BigQuery",
      schedule: "every 30 minutes",
      tables: ["tickets", "ticket_comments", "users", "organizations"],
      notes: "Full historical backfill enabled. Includes SLA and CSAT custom fields."
    })
  },
  {
    match: /postgres|postgresql/i,
    build: () => ({
      id: `conn_postgres_${Date.now().toString(36).slice(-4)}`,
      name: "PostgreSQL \u2192 BigQuery (CDC)",
      source: "PostgreSQL",
      destination: "BigQuery",
      schedule: "every 15 minutes",
      tables: ["orders", "inventory", "customers"],
      notes: "Change-data-capture via logical replication. Requires read replica."
    })
  },
  {
    match: /salesforce|crm/i,
    build: () => ({
      id: `conn_salesforce_${Date.now().toString(36).slice(-4)}`,
      name: "Salesforce \u2192 BigQuery",
      source: "Salesforce",
      destination: "BigQuery",
      schedule: "every 30 minutes",
      tables: ["accounts", "opportunities", "contacts", "leads"],
      notes: "Standard objects synced. Custom objects can be added post-setup."
    })
  },
  {
    match: /ga4|analytics|google analytics/i,
    build: () => ({
      id: `conn_ga4_${Date.now().toString(36).slice(-4)}`,
      name: "GA4 \u2192 BigQuery",
      source: "Google Analytics 4",
      destination: "BigQuery",
      schedule: "every 1 hour",
      tables: ["events_daily", "events_intraday", "user_properties"],
      notes: "Includes event_params flattening. Schema auto-update recommended."
    })
  },
  {
    match: /marketo|marketing/i,
    build: () => ({
      id: `conn_marketo_${Date.now().toString(36).slice(-4)}`,
      name: "Marketo \u2192 BigQuery",
      source: "Marketo",
      destination: "BigQuery",
      schedule: "every 6 hours",
      tables: ["leads", "campaigns", "activities", "programs"],
      notes: "Lead activity and campaign attribution tables included."
    })
  }
];
function fallbackProposal(description) {
  const slug = description.slice(0, 30).replace(/\W+/g, "_").toLowerCase() || "custom";
  return {
    id: `conn_${slug}_${Date.now().toString(36).slice(-4)}`,
    name: `Custom Pipeline \u2192 BigQuery`,
    source: "Custom API",
    destination: "BigQuery",
    schedule: "every 1 hour",
    tables: ["raw_events", "processed_events"],
    notes: `AI-generated config from: "${description.slice(0, 120)}"`
  };
}
function parseGeminiJson(text) {
  try {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return null;
    const parsed2 = JSON.parse(match[0]);
    if (parsed2.id && parsed2.name && parsed2.source) return parsed2;
    return null;
  } catch {
    return null;
  }
}
async function callGeminiForProposal(description) {
  if (config.GEMINI_API_KEY === "your_gemini_api_key" || !config.GEMINI_API_KEY) {
    return null;
  }
  const systemPrompt = `You are a data pipeline architect. Given a user's connector description, return ONLY valid JSON (no markdown) matching this schema:
{
  "id": "conn_<source>_<shortid>",
  "name": "<Source> \u2192 BigQuery (<context>)",
  "source": "<source system>",
  "destination": "BigQuery",
  "schedule": "<cron-like string e.g. every 15 minutes>",
  "tables": ["table1", "table2"],
  "notes": "<setup notes>"
}`;
  const body = {
    model: "gemini-2.0-flash",
    input: `${systemPrompt}

User request: ${description}`
  };
  try {
    const resp = await fetch(INTERACTIONS_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": config.GEMINI_API_KEY,
        "Api-Revision": "2026-05-20"
      },
      body: JSON.stringify(body)
    });
    const data = await resp.json();
    const text = data.output_text ?? data.steps?.flatMap((s) => s.content?.map((c) => c.text).filter(Boolean) ?? []).join("") ?? "";
    return parseGeminiJson(text);
  } catch {
    return null;
  }
}
function keywordProposal(description) {
  for (const { match, build } of KEYWORD_PATTERNS) {
    if (match.test(description)) return build(description);
  }
  return fallbackProposal(description);
}
async function proposeConnector(description) {
  const trimmed = description.trim();
  if (!trimmed) {
    throw new Error("description is required");
  }
  const fromGemini = await callGeminiForProposal(trimmed);
  const proposal = fromGemini ?? keywordProposal(trimmed);
  const source = fromGemini ? "gemini" : "keyword_fallback";
  return {
    proposal,
    source,
    generatedAt: (/* @__PURE__ */ new Date()).toISOString()
  };
}

// src/routes/ai.ts
var router7 = (0, import_express7.Router)();
router7.post("/propose-connector", async (req, res, next) => {
  try {
    const { description } = req.body;
    if (!description?.trim()) {
      res.status(400).json({ error: "description is required" });
      return;
    }
    const result = await proposeConnector(description.trim());
    res.json(result);
  } catch (err) {
    next(err);
  }
});
var ai_default = router7;

// src/app.ts
function createApp() {
  const app2 = (0, import_express8.default)();
  const allowedOrigins = [config.FRONTEND_ORIGIN, config.VERCEL_URL].filter(
    (o) => Boolean(o)
  );
  app2.use(
    (0, import_cors.default)({
      origin: config.NODE_ENV === "development" ? true : allowedOrigins,
      credentials: true
    })
  );
  app2.use(import_express8.default.json());
  app2.get("/health", (_req, res) => {
    res.json({ ok: true });
  });
  app2.use("/api/fivetran", fivetran_default);
  app2.use("/api/elastic", elastic_default);
  app2.use("/api/mongo", mongo_default);
  app2.use("/api/bigquery", bigquery_default);
  app2.use("/api/chat", chat_default);
  app2.use("/api/intelligence", intelligence_default);
  app2.use("/api/ai", ai_default);
  app2.use((err, _req, res, _next) => {
    console.error("[error]", err.message, err.stack);
    res.status(500).json({ error: err.message || "Internal server error" });
  });
  return app2;
}
var app = createApp();
var app_default = app;
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  createApp
});
module.exports = module.exports.default || module.exports;
